FROM postgres:14-alpine

WORKDIR /docker-entrypoint-initdb.d

COPY db.sql .

EXPOSE 5432

CMD ["docker-entrypoint.sh", "postgres"]

#to run this file:
#docker build -t your-image-name .
#docker run --env-file .env your-image-name
#docker build -t hftamayo/pgrestapi:0.0.1 .
#docker run --name pgrestapi -p 5432:5432 -d --env-file .env hftamayo/pgrestapi:0.0.1
#docker start pgrestapi